# A simple workflow
name: A Simple Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  simple-job:
    name: Simple Job
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello from ${{ github.actor }}. Checking out..."
          echo "My variable is ${{ github.MY_VARIABLE }}."
          echo "My secret is ${{ github.MY_SECRET }}."
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - run: tree
